default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: OABExams_development

test:
  <<: *default
  database: OABExams_test

production:
  <<: *default
  database: OABExams_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>

