{
    #direito eleitoral
    title: "No ano anterior à realização de eleições para cargos eletivos federais e estaduais, os dirigentes dos partidos políticos Alfa e Gama iniciaram tratativas para se aliançarem, tanto nas eleições majoritárias como nas proporcionais, mas havia dúvida em relação ao modelo a ser utilizado. Após consultarem a legislação de regência, concluíram corretamente que deveriam formar  ",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "coligação, que se extinguirá ao fim do prazo para o ajuizamento da ação de impugnação de mandato eletivo.",
    option_2: "gestão colegiada, somente utilizada nas eleições proporcionais, que deve perdurar até o fim do prazo do mandato eletivo obtido.",
    option_3: "ajuntamento partidário, que se extinguirá após a diplomação dos eleitos.",
    option_4: "federação, sendo que os partidos devem permanecer filiados por no mínimo quatro anos, contados da data do respectivo ingresso.",
    option_5: "",
    correct_answer: 3,
    available: true,
    law_area_id: 10
  },

  {
    #direito do trabalho
    title: " Francisco é caseiro desde 2019 em uma chácara localizada em área urbana, cujo proprietário aluga o imóvel por temporada por meio de um site especializado neste tipo de negociação. Francisco tem a incumbência de manter limpa a casa, receber os locatários e atender às eventuais necessidades deles no tocante ao conforto e à segurança. Além disso, de 2ª feira a sábado, Francisco faz a manutenção geral do local, independentemente de estar locado, para que a aparência esteja sempre impecável e, assim, os hóspedes recomendem a estadia na chácara a outros candidatos. Diante desta situação e das normas de regência, assinale a opção que indica a categoria profissional de Francisco. ",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "Trabalhador intermitente",
    option_2: "Empregado doméstico. ",
    option_3: "Empregado rural. ",
    option_4: "Empregado comum. ",
    option_5: "",
    correct_answer: 3,
    available: true,
    law_area_id: 5
  },

  {
    #direito do penal
    title: " Bruno, 20 anos, residente no Rio de Janeiro/RJ, conduzia seu veículo de madrugada com destino à cidade de São Paulo/SP. Bruno dirigia dentro da velocidade permitida, portando sua carteira de habilitação e seu veículo apresentava condições adequadas de tráfego. Em determinado momento, André, 21 anos, que conduzia uma motocicleta alcoolizado, na outra mão, entrou na faixa na qual trafegava Bruno, violando a regra legal de mudança de faixa de rolamento. Bruno não conseguiu frear o veículo e evitar o contato. O veículo e a motocicleta chocaram-se lateralmente. Na sequência, André caiu da moto e esbarrou num fio de alta tensão que estava rompido de um poste na estrada. Bruno, assustado com o ocorrido, acelerou seu veículo, em retirada. Após 1 km, avistou um posto policial, mas acometido por forte emoção, optou por não parar para comunicar o fato. André permaneceu em coma por uma semana e depois veio a óbito. O laudo de necropsia constatou que a causa mortis fora determinada por eletrocussão, em razão do contato com o fio de alta tensão. Pelas razões expostas, analise penalmente as condutas praticadas por Bruno e assinale a afirmativa correta.",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "Deverá ser penalmente responsabilizado por omissão de socorro (Art. 304 do CTB), tendo em vista que o resultado morte foi determinado por culpa exclusiva da vítima.",
    option_2: "Ele não praticou crime algum, porque a presença de concausa independente afasta a imputação de homicídio culposo, assim como a violenta emoção afasta a tipicidade do crime de omissão de socorro.",
    option_3: "Deverá ser penalmente responsabilizado por homicídio culposo na condução de veículo, com a incidência da causa de aumento de omissão de socorro.",
    option_4: "Bruno deverá ser penalmente responsabilizado por homicídio culposo na condução de veículo e omissão de socorro, em concurso material.",
    option_5: "",
    correct_answer: 0,
    available: true,
    law_area_id: 2
  }, 
  {
    #direito ambiental
    title: "Tramita na Câmara do Município Alfa projeto de lei que dispõe sobre proteção ao meio ambiente no âmbito de seu território, observado o interesse local. Sabe-se que o projeto de lei está harmônico com a disciplina legislativa estadual e federal atualmente vigente. No caso em tela, em matéria de competência legislativa ambiental, de acordo com a CRFB/88, é correto afirmar que o projeto de lei, em tese,",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "ofende a Carta Magna, porque compete à União legislar privativamente sobre proteção ao meio ambiente, observadas as premissas constitucionais.",
    option_2: "é incompatível com a Carta Magna, porque compete à União, aos Estados e ao Distrito Federal legislar privativamente sobre proteção ao meio ambiente.",
    option_3: "não viola a Carta Magna, porque o Município possui competência suplementar à da União e à dos Estados para legislar sobre proteção ao meio ambiente, no limite do seu interesse local e desde que tal regramento seja harmônico com a disciplina estabelecida pelos demais entes federados.",
    option_4: "não afronta a Carta Magna, porque o Município possui competência concorrente e não suplementar com a União e os Estados para legislar sobre proteção ao meio ambiente, de maneira que pode dispor de forma diversa e menos protetiva ao ambiente do que a disciplina estadual.",
    option_5: "",
    correct_answer: 2,
    available: true,
    law_area_id: 9
  },
  {
    #direito civil 
    title: "O cidadão francês Pierre Renoir, residente e domiciliado em Portugal, foi casado com uma espanhola, com quem teve dois filhos nascidos na Alemanha. Pierre faleceu em 2022 e deixou como herança um apartamento no Brasil, onde viveu durante a fase universitária.
    Nesta hipótese, à sucessão do bem será aplicada a lei.",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "francesa.",
    option_2: "portuguesa.",
    option_3: "brasileira.",
    option_4: "alemã.",
    option_5: "",
    correct_answer: 1,
    available: true,
    law_area_id: 1
  },
  {
    #direito tributario 
    title: "A Sociedade Empresária Aguardente 100% Ltda., fabricante de bebidas destiladas, por meio de sua advogada Sophia, protocolou perante a Secretaria Especial da Receita Federal do Brasil, ainda dentro do prazo legal para pagamento, consulta referente à necessidade de recolhimento de Imposto sobre Produtos Industrializados (IPI) acerca de operação específica por ela desempenhada.Escoado o prazo original para pagamento e ainda não decidida a consulta, à luz do Código Tributário Nacional (CTN) assinale a afirmativa correta.",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "Aguardente 100% Ltda. poderá ter cobrados contra si juros de mora que correm mesmo na pendência da consulta tributária.",
    option_2: "Por ocasião da decisão final da consulta, o Fisco federal poderá impor multa tributária caso a solução de consulta seja contrária aos interesses de Aguardente 100% Ltda.",
    option_3: "A obrigação tributária a ser cumprida por Aguardente 100% Ltda., por ter sido objeto de consulta, não poderá ser acrescida de juros de mora e nem poderá ser imposta multa tributária à empresa.",
    option_4: "Podem ser aplicadas contra Aguardente 100% Ltda. medidas de garantia previstas no CTN ou em lei tributária na pendência da consulta tributária.",
    option_5: "",
    correct_answer: 2,
    available: true,
    law_area_id: 6
  },
  {
    #direito Administrativo
    title: "Josias e Januário são servidores públicos federais de alta hierarquia e estavam conversando sobre os problemas inerentes ao exercício de suas atribuições. Enquanto Josias está extremamente exacerbado de trabalho e precisa delegar algumas de suas atribuições, para não comprometer o funcionamento da atividade administrativa, Januário entende ser necessário avocar competência atribuída a órgão hierarquicamente inferior, por questões excepcionais que são de extrema relevância para o interesse público. Considerando as circunstâncias narradas, em consonância com a Lei nº 9.784/99, assinale a afirmativa correta.",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "Josias poderá delegar verbalmente parcela de sua competência, considerando que esta é renunciável por servidor de alta hierarquia.",
    option_2: "Eventual delegação de competência por parte de Josias não poderá ser revogada após a sua formalização.",
    option_3: "A delegação de competência por Josias só pode ser realizada para órgão que lhe seja hierarquicamente inferior.",
    option_4: "A avocação temporária de competência por Januário será permitida em caráter excepcional e por motivos relevantes devidamente justificados.",
    option_5: "",
    correct_answer: 4,
    available: true,
    law_area_id: 4
  },
  {
    #direito processual penal
    title: "Luciane ajuizou na Vara Criminal da Comarca de Romã (ES) uma ação penal privada contra Jorge (guarda municipal daquele município) por crime de injúria (Art. 140, caput, do CP). Antes de oferecer a queixa-crime, Luciane propôs uma ação cível de indenização contra Jorge e não conseguiu citá-lo pessoalmente em sua residência, sita no próprio Município de Romã (ES), tendo em vista que o oficial de justiça certificou que esteve em duas oportunidades na casa de Jorge e não o localizou. Luciane foi informada por vizinhos que Jorge estava temporariamente residindo com sua mãe na cidade vizinha de Oeiras (ES), onde ela já havia passado um final de semana. Em se tratando de infração penal de menor potencial ofensivo, você, como advogado(a) da querelante, deverá, na ação penal privada, requerer a citação de Jorge",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "por intermédio do seu chefe de serviço, em razão de Jorge ser guarda municipal, expedindo-se ofício ao comandante da Guarda Municipal.",
    option_2: "por hora certa, haja vista que Jorge estava se ocultando para não ser encontrado.",
    option_3: "por carta precatória, visto que Jorge está residindo temporariamente fora da jurisdição do juiz processante, considerando que a querelante tinha conhecimento do endereço da mãe do querelado na Comarca de Oeiras (ES).",
    option_4: "por correspondência com aviso de recebimento em mão própria, considerando que a querelante tinha conhecimento do endereço da mãe do querelado na Comarca de Oeiras (ES).",
    option_5: "",
    correct_answer: 2,
    available: true,
    law_area_id: 17
  },
  {
    #direito da Infância e Juventude
    title: "A mãe de Joaquim, criança com necessidades especiais, requereu acompanhamento por professor especializado em atendimento de pessoas com deficiência à escola-creche pública municipal em que o filho estuda. A escola-creche, no entanto, alegou carência de tais profissionais, porque o custo muito alto impedia que a municipalidade os contratasse. Ao consultar você, como advogado(a), a genitora recebeu a seguinte orientação.",
    evaluation_board: "FGV",
    year: "2023",
    option_1: "A criança tem direito à educação, não se inserindo nesse plexo, porém, o direito individual e específico de acompanhamento especializado.",
    option_2: "Joaquim deve ter acesso à educação com metodologia especial, não significando, porém, que seja mandatória a presença de profissional especial.",
    option_3: "A atenção especial por profissional especializado é devida a Joaquim, não sendo oponível a dificuldade orçamentária declarada pela municipalidade.",
    option_4: "O ensino especializado é devido nas condições em que a entidade for capaz, não sendo obrigatória a presença de profissional especificamente capacitado, em razão da aplicabilidade da reserva do possível.",
    option_5: "",
    correct_answer: 2,
    available: true,
    law_area_id: 21
  }, 

  #Novas questões
  {
    title: "João, proprietário de um imóvel, decidiu alugá-lo a Maria. No entanto, ao longo do contrato de locação, João constatou que Maria não havia pago dois meses consecutivos de aluguel. Em relação a essa situação, a qual medida João pode recorrer?",
    evaluation_board: "FGV",
    year: "2021",
    option_1: "João não pode rescindir o contrato de locação, pois o não pagamento não configura infração grave.",
    option_2: "João pode rescindir o contrato de locação, caso Maria não pague os aluguéis em atraso dentro do prazo de 30 dias.",
    option_3: "João deve conceder um novo prazo de 60 dias para o pagamento dos aluguéis em atraso.",
    option_4: "João pode solicitar apenas o pagamento do valor em atraso, mas não pode rescindir o contrato.",
    correct_answer: 2,
    available: true,
    law_area_id: 1
  },
  {
    title: "Carlos foi acusado de roubo, mas a defesa sustenta que ele agiu sob coação moral irresistível, sendo forçado a cometer o crime por uma ameaça direta à sua vida. Qual é o fundamento jurídico dessa defesa?",
    evaluation_board: "OAB",
    year: "2022",
    option_1: "A coação moral irresistível exclui a culpabilidade de Carlos, pois o ato foi praticado sem dolo.",
    option_2: "Carlos pode ser absolvido, pois a coação moral irresistível constitui causa de isenção de pena.",
    option_3: "Carlos deve ser condenado, mas sua pena pode ser atenuada pela coação moral irresistível.",
    option_4: "A defesa de coação moral irresistível não é cabível no Direito Penal brasileiro.",
    correct_answer: 1,
    available: true,
    law_area_id: 2
  },
  {
    title: "O Presidente da República propôs uma emenda à Constituição, que visava alterar direitos fundamentais de uma categoria de trabalhadores. Qual princípio constitucional é violado por essa proposta?",
    evaluation_board: "FCC",
    year: "2023",
    option_1: "Violação do princípio da separação dos Poderes.",
    option_2: "Violação do princípio da supremacia da Constituição.",
    option_3: "Violação do princípio da vedação ao retrocesso social.",
    option_4: "Violação do princípio da publicidade dos atos administrativos.",
    correct_answer: 3,
    available: true,
    law_area_id: 3
  },
  {
    title: "Uma autarquia pública, após a nomeação de um servidor concursado, decide revogar o seu ato administrativo, alegando necessidade de reestruturação interna. Qual é a natureza dessa revogação?",
    evaluation_board: "CESPE",
    year: "2020",
    option_1: "É uma revogação de ato administrativo vinculada, pois a Administração Pública tem liberdade para revogar o ato.",
    option_2: "É uma revogação discricionária, pois a Administração Pública pode revogar atos administrativos por conveniência administrativa.",
    option_3: "É uma revogação ilegal, pois não há possibilidade de revogar atos administrativos relacionados à nomeação de servidores concursados.",
    option_4: "É uma anulação do ato administrativo, uma vez que a nomeação do servidor é inválida.",
    correct_answer: 3,
    available: true,
    law_area_id: 4
  },
  {
    title: "Em uma ação trabalhista, o trabalhador pleiteia a aplicação de normas mais benéficas à sua condição, com base no princípio da condição mais favorável. Qual situação caracteriza o princípio da condição mais favorável?",
    evaluation_board: "OAB",
    year: "2021",
    option_1: "A aplicação das normas mais benéficas ao trabalhador quando há conflito entre normas de diferentes fontes, favorecendo a parte mais vulnerável.",
    option_2: "A aplicação das normas mais benéficas ao trabalhador, independentemente de sua relação com as normas coletivas da categoria.",
    option_3: "O princípio da condição mais favorável permite que o empregador implemente condições de trabalho mais favoráveis ao empregado, se assim desejar.",
    option_4: "O princípio da condição mais favorável se aplica exclusivamente ao trabalhador urbano, não podendo ser invocado pelo trabalhador rural.",
    correct_answer: 1,
    available: true,
    law_area_id: 5
  },
  {
    title: "Uma empresa questiona a legalidade da cobrança de um imposto estadual, alegando que a forma de cálculo utilizada pelo Fisco fere o princípio da legalidade tributária. Qual é o fundamento legal que deve ser aplicado para avaliar esse caso?",
    evaluation_board: "VUNESP",
    year: "2022",
    option_1: "A cobrança do imposto deve ser analisada à luz do princípio da anterioridade, que exige que o imposto seja publicado com antecedência.",
    option_2: "A cobrança do imposto deve ser analisada à luz do princípio da legalidade, que proíbe a cobrança de tributo sem lei que a autorize.",
    option_3: "A empresa pode contestar a cobrança com base no princípio da capacidade contributiva, que limita os impostos conforme a situação financeira do contribuinte.",
    option_4: "A cobrança do imposto é válida, pois se baseia na norma infralegal, desde que não contrarie a Constituição.",
    correct_answer: 2,
    available: true,
    law_area_id: 6
  },
  {
    title: "O contrato social de uma sociedade anônima foi alterado sem a devida formalização, ou seja, sem o cumprimento dos requisitos legais para alterações estatutárias. Nesse caso, qual é a consequência jurídica dessa omissão?",
    evaluation_board: "CESPE",
    year: "2021",
    option_1: "A alteração contratual é válida, pois a forma de celebração do ato não afeta a sua substância.",
    option_2: "A alteração contratual é considerada nula, uma vez que não observados os requisitos legais para sua formalização.",
    option_3: "A alteração contratual é válida, mas a sociedade pode ser responsabilizada pela omissão quanto à formalização de documentos.",
    option_4: "A alteração contratual não tem efeitos, mas a sociedade pode regularizar o procedimento em até 30 dias após a verificação da irregularidade.",
    correct_answer: 2,
    available: true,
    law_area_id: 7
  },
  {
    title: "Em uma situação de disputa internacional sobre a posse de uma ilha, qual princípio do Direito Internacional é relevante para decidir quem tem a soberania sobre o território?",
    evaluation_board: "FGV",
    year: "2020",
    option_1: "O princípio da auto-determinação dos povos.",
    option_2: "O princípio da solução pacífica dos conflitos.",
    option_3: "O princípio da uti possidetis, que assegura o direito à posse de terras conforme a situação pré-existente.",
    option_4: "O princípio da soberania territorial e o direito internacional consuetudinário.",
    correct_answer: 4,
    available: true,
    law_area_id: 8
  },
  {
    title: "Em relação às questões ambientais, qual é o princípio que determina que os danos ao meio ambiente devem ser reparados, independentemente da existência de culpa ou dolo do agente causador?",
    evaluation_board: "OAB",
    year: "2022",
    option_1: "O princípio da precaução.",
    option_2: "O princípio da responsabilidade objetiva.",
    option_3: "O princípio da prevenção.",
    option_4: "O princípio da participação pública.",
    correct_answer: 2,
    available: true,
    law_area_id: 9
  },
  {
    title: "Um candidato a um cargo público contesta a regularidade de uma eleição, alegando fraude nos procedimentos de apuração dos votos. Qual é o órgão competente para julgar essa ação?",
    evaluation_board: "CESPE",
    year: "2023",
    option_1: "O Tribunal Superior Eleitoral (TSE), por ser a instância máxima da Justiça Eleitoral.",
    option_2: "O Supremo Tribunal Federal (STF), devido à relevância constitucional da matéria.",
    option_3: "O Tribunal Regional Eleitoral (TRE), responsável pelo julgamento de todas as ações relativas a eleições no âmbito estadual.",
    option_4: "O Tribunal de Contas da União (TCU), por tratar de irregularidades nos atos administrativos.",
    correct_answer: 1,
    available: true,
    law_area_id: 10
  },
  {
    title: "Sobre o regime de bens no casamento, qual dos seguintes regimes não permite que os bens adquiridos por um dos cônjuges sejam comunicados ao outro?",
    evaluation_board: "FGV",
    year: "2020",
    option_1: "Regime da separação de bens.",
    option_2: "Regime da comunhão parcial de bens.",
    option_3: "Regime da comunhão universal de bens.",
    option_4: "Regime da participação final nos aquestos.",
    correct_answer: 1,
    available: true,
    law_area_id: 1
  },
  {
    title: "Em relação à responsabilidade civil, é correto afirmar que:",
    evaluation_board: "OAB",
    year: "2021",
    option_1: "A responsabilidade civil objetiva depende de comprovação de culpa do agente.",
    option_2: "A responsabilidade civil subjetiva prescinde da comprovação do dano causado.",
    option_3: "A responsabilidade civil objetiva independe de culpa, baseando-se no risco da atividade.",
    option_4: "A responsabilidade civil objetiva é limitada apenas ao dano material.",
    correct_answer: 3,
    available: true,
    law_area_id: 1
  },
  {
    title: "João foi condenado pelo crime de roubo, mas ao recorrer alegou que agiu em legítima defesa. Qual das situações abaixo caracteriza a legítima defesa?",
    evaluation_board: "CESPE",
    year: "2022",
    option_1: "João agiu para proteger um bem seu, mas de forma desproporcional.",
    option_2: "João agiu para defender um bem de outra pessoa, sem exagerar na reação.",
    option_3: "João agiu em um momento de grande medo, mas sem um ataque real a sua integridade.",
    option_4: "João agiu para defender a honra, mas sem um ataque imediato à sua pessoa.",
    correct_answer: 2,
    available: true,
    law_area_id: 2
  },
  {
    title: "Em relação ao controle de constitucionalidade, qual é a característica da ação direta de inconstitucionalidade (ADI)?",
    evaluation_board: "FCC",
    year: "2023",
    option_1: "A ADI visa a declarar a nulidade de normas infraconstitucionais.",
    option_2: "A ADI é utilizada exclusivamente para atacar leis estaduais, sendo restrita a normas federais.",
    option_3: "A ADI pode ser ajuizada por qualquer pessoa, independentemente de legitimidade.",
    option_4: "A ADI visa a declarar a inconstitucionalidade de normas com efeitos para todo o ordenamento jurídico.",
    correct_answer: 4,
    available: true,
    law_area_id: 3
  },
  {
    title: "O servidor público João cometeu uma infração administrativa em seu local de trabalho. De acordo com o regime jurídico dos servidores públicos, qual é a punição aplicável para essa infração?",
    evaluation_board: "VUNESP",
    year: "2021",
    option_1: "A punição será uma advertência verbal, sendo a única aplicável a infrações leves.",
    option_2: "A punição será a demissão, somente em casos de infrações graves e reiteradas.",
    option_3: "A punição dependerá de processo administrativo disciplinar, conforme a gravidade da infração.",
    option_4: "A punição não poderá ser aplicada sem a prévia oitiva do superior hierárquico do servidor.",
    correct_answer: 3,
    available: true,
    law_area_id: 4
  },
  {
    title: "O trabalhador urbano que presta serviços em uma empresa, mas sem vínculo empregatício, caracteriza-se como:",
    evaluation_board: "OAB",
    year: "2021",
    option_1: "Trabalhador autônomo.",
    option_2: "Trabalhador temporário.",
    option_3: "Trabalhador terceirizado.",
    option_4: "Trabalhador informal.",
    correct_answer: 1,
    available: true,
    law_area_id: 5
  },
  {
    title: "De acordo com o Código Tributário Nacional, qual é o conceito de tributo?",
    evaluation_board: "CESPE",
    year: "2022",
    option_1: "Tributo é toda prestação pecuniária compulsória, em dinheiro, destinada a uma pessoa jurídica de direito público.",
    option_2: "Tributo é uma contribuição espontânea que o contribuinte faz ao Estado.",
    option_3: "Tributo é qualquer forma de pagamento voluntário feito ao Estado.",
    option_4: "Tributo é uma dívida contraída pelo contribuinte com o Estado para o financiamento de serviços públicos.",
    correct_answer: 1,
    available: true,
    law_area_id: 6
  },
  {
    title: "Em uma sociedade limitada, qual é o valor mínimo de capital social exigido por lei?",
    evaluation_board: "FGV",
    year: "2020",
    option_1: "Não há exigência mínima de capital social.",
    option_2: "R$ 1.000,00, conforme a legislação vigente.",
    option_3: "R$ 10.000,00, conforme a legislação vigente.",
    option_4: "R$ 100.000,00, conforme a legislação vigente.",
    correct_answer: 1,
    available: true,
    law_area_id: 7
  },
  {
    title: "Em relação ao tratado internacional sobre meio ambiente, qual é o princípio que obriga os países a prevenir a poluição e minimizar os danos ambientais?",
    evaluation_board: "OAB",
    year: "2023",
    option_1: "Princípio da precaução.",
    option_2: "Princípio da prevenção.",
    option_3: "Princípio da cooperação internacional.",
    option_4: "Princípio da responsabilidade por danos transfronteiriços.",
    correct_answer: 1,
    available: true,
    law_area_id: 9
  },
  {
    title: "Qual é a função do Tribunal Superior Eleitoral (TSE)?",
    evaluation_board: "CESPE",
    year: "2022",
    option_1: "Organizar as eleições, apurar os votos e proclamar os resultados.",
    option_2: "Julgar os recursos eleitorais das instâncias inferiores.",
    option_3: "Zelar pela observância dos princípios constitucionais nas eleições.",
    option_4: "Propor novas leis eleitorais ao Congresso Nacional.",
    correct_answer: 1,
    available: true,
    law_area_id: 10
  },
  {
    title: "Em relação à disputa entre países por recursos naturais em zonas oceânicas, qual é o princípio que rege a partilha desses recursos?",
    evaluation_board: "FCC",
    year: "2023",
    option_1: "Princípio da liberdade dos mares.",
    option_2: "Princípio da soberania nacional.",
    option_3: "Princípio da apropriação exclusiva.",
    option_4: "Princípio da gestão compartilhada.",
    correct_answer: 4,
    available: true,
    law_area_id: 8
  },
  {
    title: "Um tratado internacional foi assinado entre dois países, mas um deles não ratificou o acordo devido a incompatibilidades internas com a sua Constituição. O que deve ser feito?",
    evaluation_board: "VUNESP",
    year: "2020",
    option_1: "O tratado deve ser revogado, pois não tem validade sem a ratificação.",
    option_2: "O tratado pode ser ratificado unilateralmente pelo outro país, sem necessidade de modificação.",
    option_3: "O tratado entra em vigor assim que um dos países ratificar, mesmo sem a ratificação do outro.",
    option_4: "O tratado só entra em vigor se ambos os países ratificarem, conforme a Constituição de cada um.",
    correct_answer: 4,
    available: true,
    law_area_id: 8
  }